<?php

if (!defined('ABSPATH')) {
    exit;
}

return [
    "age_gator_age" => "21",
    "age_gator_auto_submit" => "1",
    "age_gator_background_color" => "#000000",
    "age_gator_background_image" => "",
    "age_gator_background_opacity" => "82",
    "age_gator_blacklist" => "",
    "age_gator_button_text_color" => "",
    "age_gator_bypass_logged_in_users" => "",
    "age_gator_checkbox_text" => "I confirm that I am [AGE] years old or older",
    "age_gator_disclaimer" => "By entering this site you are agreeing to our terms of use and privacy policy.",
    "age_gator_fail" => "Whoops! You cannot enter the site!",
    "age_gator_fail_button_text" => "No",
    "age_gator_guarding" => "all",
    "age_gator_heading" => "Let's see some I.D.",
    "age_gator_heading_color" => "#000000",
    "age_gator_heading_fontfamily" => "serif",
    "age_gator_heading_fontsize_desktop" => "40",
    "age_gator_heading_fontsize_mobile" => "38",
    "age_gator_heading_manual_fontfamily" => false,
    "age_gator_heading_manual_fontsize" => "1",
    "age_gator_limit_attempts" => false,
    "age_gator_lock_time" => "30",
    "age_gator_max_attempts" => "1",
    "age_gator_max_width" => "840",
    "age_gator_message_color" => "#000000",
    "age_gator_modal_color" => "#f0d283",
    "age_gator_modal_image" => "",
    "age_gator_modal_image2" => "",
    "age_gator_modal_image_width" => "150",
    "age_gator_modal_padding_percent" => "10",
    "age_gator_modal_padding_px" => "40",
    "age_gator_modal_padding_units" => "pixels",
    "age_gator_modal_text_color" => "",
    "age_gator_pass_button_text" => "Yes",
    "age_gator_precheck_checkbox" => false,
    "age_gator_primary_button_background_color" => "#343434",
    "age_gator_primary_button_text_color" => "",
    "age_gator_prompt" => "Friends don’t let friends enter brewery websites unless they’re [AGE] years old. Are you of age?",
    "age_gator_prompt_delay_length" => "600",
    "age_gator_remember_user" => false,
    "age_gator_remember_user_time" => "30",
    "age_gator_retry_button" => false,
    "age_gator_retry_button_text" => "Retry",
    "age_gator_secondary_button_background_color" => "#333333",
    "age_gator_submit_button_text" => "Submit",
    "age_gator_success" => "Welcome to the site!",
    "age_gator_success_delay_length" => "600",
    "age_gator_template" => "beer",
    "age_gator_type" => "button",
    "age_gator_whitelist" => "",
];
