<?php

if (!defined('ABSPATH')) {
    exit;
}

return [
    "age_gator_age" => "19",
    "age_gator_auto_submit" => "1",
    "age_gator_background_color" => "#212121",
    "age_gator_background_image" => "",
    "age_gator_background_opacity" => "95",
    "age_gator_blacklist" => "",
    "age_gator_button_text_color" => "",
    "age_gator_bypass_logged_in_users" => "",
    "age_gator_checkbox_text" => "I confirm that I am [AGE] years old or older",
    "age_gator_disclaimer" => "By entering this site you are agreeing to our terms of use and privacy policy.",
    "age_gator_fail" => "Whoops! You cannot enter the site!",
    "age_gator_fail_button_text" => "No",
    "age_gator_guarding" => "all",
    "age_gator_heading" => "",
    "age_gator_heading_color" => "#004d40",
    "age_gator_heading_fontfamily" => "serif",
    "age_gator_heading_fontsize_desktop" => "40",
    "age_gator_heading_fontsize_mobile" => "38",
    "age_gator_heading_manual_fontfamily" => false,
    "age_gator_heading_manual_fontsize" => "1",
    "age_gator_limit_attempts" => false,
    "age_gator_lock_time" => "30",
    "age_gator_max_attempts" => "1",
    "age_gator_max_width" => "840",
    "age_gator_message_color" => "#004d40",
    "age_gator_modal_color" => "#ffffff",
    "age_gator_modal_image" => "",
    "age_gator_modal_image2" => "http://localhost:3000/wp-content/uploads/2019/10/marijuana_age_gator.jpg",
    "age_gator_modal_image_width" => "150",
    "age_gator_modal_padding_percent" => "10",
    "age_gator_modal_padding_px" => "40",
    "age_gator_modal_padding_units" => "pixels",
    "age_gator_modal_text_color" => "#004d40",
    "age_gator_pass_button_text" => "Yes",
    "age_gator_precheck_checkbox" => false,
    "age_gator_primary_button_background_color" => "#004d40",
    "age_gator_primary_button_text_color" => "#ffffff",
    "age_gator_prompt" => "Please confirm that you are at least [AGE] years old for full access to the Cannabis Store website.",
    "age_gator_prompt_delay_length" => "600",
    "age_gator_remember_user" => false,
    "age_gator_remember_user_time" => "30",
    "age_gator_retry_button" => false,
    "age_gator_retry_button_text" => "Retry",
    "age_gator_secondary_button_background_color" => "#004d40",
    "age_gator_submit_button_text" => "Enter",
    "age_gator_success" => "Welcome to the site!",
    "age_gator_success_delay_length" => "600",
    "age_gator_template" => "marijuana",
    "age_gator_type" => "checkbox",
    "age_gator_whitelist" => "",
];
